/* This file was generated by SableCC (http://www.sablecc.org/). */

package joosc.node;

import joosc.analysis.*;

@SuppressWarnings("nls")
public final class ACharconstExp extends PExp
{
    private TCharconst _charconst_;

    public ACharconstExp()
    {
        // Constructor
    }

    public ACharconstExp(
        @SuppressWarnings("hiding") TCharconst _charconst_)
    {
        // Constructor
        setCharconst(_charconst_);

    }

    @Override
    public Object clone()
    {
        return new ACharconstExp(
            cloneNode(this._charconst_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseACharconstExp(this);
    }

    public TCharconst getCharconst()
    {
        return this._charconst_;
    }

    public void setCharconst(TCharconst node)
    {
        if(this._charconst_ != null)
        {
            this._charconst_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._charconst_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._charconst_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._charconst_ == child)
        {
            this._charconst_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._charconst_ == oldChild)
        {
            setCharconst((TCharconst) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
