/* This file was generated by SableCC (http://www.sablecc.org/). */

package joosc.node;

import java.util.*;
import joosc.analysis.*;

@SuppressWarnings("nls")
public final class ADeclStm extends PStm
{
    private final LinkedList<POnelocal> _locals_ = new LinkedList<POnelocal>();

    public ADeclStm()
    {
        // Constructor
    }

    public ADeclStm(
        @SuppressWarnings("hiding") List<?> _locals_)
    {
        // Constructor
        setLocals(_locals_);

    }

    @Override
    public Object clone()
    {
        return new ADeclStm(
            cloneList(this._locals_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADeclStm(this);
    }

    public LinkedList<POnelocal> getLocals()
    {
        return this._locals_;
    }

    public void setLocals(List<?> list)
    {
        for(POnelocal e : this._locals_)
        {
            e.parent(null);
        }
        this._locals_.clear();

        for(Object obj_e : list)
        {
            POnelocal e = (POnelocal) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._locals_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._locals_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._locals_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        for(ListIterator<POnelocal> i = this._locals_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((POnelocal) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
