/* This file was generated by SableCC (http://www.sablecc.org/). */

package joosc.node;

import joosc.analysis.*;

@SuppressWarnings("nls")
public final class ADefaultClassfile extends PClassfile
{
    private PClass _pClass_;

    public ADefaultClassfile()
    {
        // Constructor
    }

    public ADefaultClassfile(
        @SuppressWarnings("hiding") PClass _pClass_)
    {
        // Constructor
        setPClass(_pClass_);

    }

    @Override
    public Object clone()
    {
        return new ADefaultClassfile(
            cloneNode(this._pClass_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADefaultClassfile(this);
    }

    public PClass getPClass()
    {
        return this._pClass_;
    }

    public void setPClass(PClass node)
    {
        if(this._pClass_ != null)
        {
            this._pClass_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._pClass_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._pClass_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._pClass_ == child)
        {
            this._pClass_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._pClass_ == oldChild)
        {
            setPClass((PClass) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
