/* This file was generated by SableCC (http://www.sablecc.org/). */

package joosc.node;

import joosc.analysis.*;

@SuppressWarnings("nls")
public final class AIfelseStm extends PStm
{
    private PExp _exp_;
    private PStm _thenStm_;
    private PStm _elseStm_;

    public AIfelseStm()
    {
        // Constructor
    }

    public AIfelseStm(
        @SuppressWarnings("hiding") PExp _exp_,
        @SuppressWarnings("hiding") PStm _thenStm_,
        @SuppressWarnings("hiding") PStm _elseStm_)
    {
        // Constructor
        setExp(_exp_);

        setThenStm(_thenStm_);

        setElseStm(_elseStm_);

    }

    @Override
    public Object clone()
    {
        return new AIfelseStm(
            cloneNode(this._exp_),
            cloneNode(this._thenStm_),
            cloneNode(this._elseStm_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAIfelseStm(this);
    }

    public PExp getExp()
    {
        return this._exp_;
    }

    public void setExp(PExp node)
    {
        if(this._exp_ != null)
        {
            this._exp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exp_ = node;
    }

    public PStm getThenStm()
    {
        return this._thenStm_;
    }

    public void setThenStm(PStm node)
    {
        if(this._thenStm_ != null)
        {
            this._thenStm_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._thenStm_ = node;
    }

    public PStm getElseStm()
    {
        return this._elseStm_;
    }

    public void setElseStm(PStm node)
    {
        if(this._elseStm_ != null)
        {
            this._elseStm_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._elseStm_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._exp_)
            + toString(this._thenStm_)
            + toString(this._elseStm_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._exp_ == child)
        {
            this._exp_ = null;
            return;
        }

        if(this._thenStm_ == child)
        {
            this._thenStm_ = null;
            return;
        }

        if(this._elseStm_ == child)
        {
            this._elseStm_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._exp_ == oldChild)
        {
            setExp((PExp) newChild);
            return;
        }

        if(this._thenStm_ == oldChild)
        {
            setThenStm((PStm) newChild);
            return;
        }

        if(this._elseStm_ == oldChild)
        {
            setElseStm((PStm) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
