/* This file was generated by SableCC (http://www.sablecc.org/). */

package joosc.node;

import joosc.analysis.*;

@SuppressWarnings("nls")
public final class TDouble extends Token
{
    public TDouble()
    {
        super.setText("double");
    }

    public TDouble(int line, int pos)
    {
        super.setText("double");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TDouble(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTDouble(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TDouble text.");
    }
}
