/* This file was generated by SableCC (http://www.sablecc.org/). */

package joosc.node;

import joosc.analysis.*;

@SuppressWarnings("nls")
public final class TExtern extends Token
{
    public TExtern()
    {
        super.setText("extern");
    }

    public TExtern(int line, int pos)
    {
        super.setText("extern");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TExtern(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTExtern(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TExtern text.");
    }
}
