/* This file was generated by SableCC (http://www.sablecc.org/). */

package joosc.analysis;

import java.util.*;
import joosc.node.*;

public class AnalysisAdapter implements Analysis
{
    private Hashtable<Node,Object> in;
    private Hashtable<Node,Object> out;

    @Override
    public Object getIn(Node node)
    {
        if(this.in == null)
        {
            return null;
        }

        return this.in.get(node);
    }

    @Override
    public void setIn(Node node, Object o)
    {
        if(this.in == null)
        {
            this.in = new Hashtable<Node,Object>(1);
        }

        if(o != null)
        {
            this.in.put(node, o);
        }
        else
        {
            this.in.remove(node);
        }
    }

    @Override
    public Object getOut(Node node)
    {
        if(this.out == null)
        {
            return null;
        }

        return this.out.get(node);
    }

    @Override
    public void setOut(Node node, Object o)
    {
        if(this.out == null)
        {
            this.out = new Hashtable<Node,Object>(1);
        }

        if(o != null)
        {
            this.out.put(node, o);
        }
        else
        {
            this.out.remove(node);
        }
    }

    @Override
    public void caseStart(Start node)
    {
        defaultCase(node);
    }

    @Override
    public void caseADefaultClassfile(ADefaultClassfile node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAExternClassfile(AExternClassfile node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAClass(AClass node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAFinalClassmods(AFinalClassmods node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAAbstractClassmods(AAbstractClassmods node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAExternClass(AExternClass node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAExtension(AExtension node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAReferenceType(AReferenceType node)
    {
        defaultCase(node);
    }

    @Override
    public void caseACharType(ACharType node)
    {
        defaultCase(node);
    }

    @Override
    public void caseABooleanType(ABooleanType node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAIntType(AIntType node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAPolynullType(APolynullType node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAVoidType(AVoidType node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAFirstField(AFirstField node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAField(AField node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAOnefield(AOnefield node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAConstructor(AConstructor node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAExternConstructor(AExternConstructor node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAFormal(AFormal node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAModMethod(AModMethod node)
    {
        defaultCase(node);
    }

    @Override
    public void caseANonmodMethod(ANonmodMethod node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAAbstractMethod(AAbstractMethod node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAMainMethod(AMainMethod node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAFinalMethodmods(AFinalMethodmods node)
    {
        defaultCase(node);
    }

    @Override
    public void caseASynchronizedMethodmods(ASynchronizedMethodmods node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAMainargv(AMainargv node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAModExternMethod(AModExternMethod node)
    {
        defaultCase(node);
    }

    @Override
    public void caseANonmodExternMethod(ANonmodExternMethod node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAFinalExternMethodmods(AFinalExternMethodmods node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAAbstractExternMethodmods(AAbstractExternMethodmods node)
    {
        defaultCase(node);
    }

    @Override
    public void caseASynchronizedExternMethodmods(ASynchronizedExternMethodmods node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAVoidReturntype(AVoidReturntype node)
    {
        defaultCase(node);
    }

    @Override
    public void caseANonvoidReturntype(ANonvoidReturntype node)
    {
        defaultCase(node);
    }

    @Override
    public void caseASkipStm(ASkipStm node)
    {
        defaultCase(node);
    }

    @Override
    public void caseABlockStm(ABlockStm node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAExpStm(AExpStm node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAReturnStm(AReturnStm node)
    {
        defaultCase(node);
    }

    @Override
    public void caseADeclFirstStm(ADeclFirstStm node)
    {
        defaultCase(node);
    }

    @Override
    public void caseADeclStm(ADeclStm node)
    {
        defaultCase(node);
    }

    @Override
    public void caseASuperconsStm(ASuperconsStm node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAIfStm(AIfStm node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAIfelseStm(AIfelseStm node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAWhileStm(AWhileStm node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAOnelocal(AOnelocal node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAAssignExp(AAssignExp node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAOrExp(AOrExp node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAAndExp(AAndExp node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAEqExp(AEqExp node)
    {
        defaultCase(node);
    }

    @Override
    public void caseANeqExp(ANeqExp node)
    {
        defaultCase(node);
    }

    @Override
    public void caseALtExp(ALtExp node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAGtExp(AGtExp node)
    {
        defaultCase(node);
    }

    @Override
    public void caseALeqExp(ALeqExp node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAGeqExp(AGeqExp node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAInstanceofExp(AInstanceofExp node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAPlusExp(APlusExp node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAMinusExp(AMinusExp node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAMultExp(AMultExp node)
    {
        defaultCase(node);
    }

    @Override
    public void caseADivExp(ADivExp node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAModExp(AModExp node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAUminusExp(AUminusExp node)
    {
        defaultCase(node);
    }

    @Override
    public void caseANotExp(ANotExp node)
    {
        defaultCase(node);
    }

    @Override
    public void caseATmpcastExp(ATmpcastExp node)
    {
        defaultCase(node);
    }

    @Override
    public void caseACastExp(ACastExp node)
    {
        defaultCase(node);
    }

    @Override
    public void caseACasttocharExp(ACasttocharExp node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAIdExp(AIdExp node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAThisExp(AThisExp node)
    {
        defaultCase(node);
    }

    @Override
    public void caseANewExp(ANewExp node)
    {
        defaultCase(node);
    }

    @Override
    public void caseACallExp(ACallExp node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAIntconstExp(AIntconstExp node)
    {
        defaultCase(node);
    }

    @Override
    public void caseATrueExp(ATrueExp node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAFalseExp(AFalseExp node)
    {
        defaultCase(node);
    }

    @Override
    public void caseACharconstExp(ACharconstExp node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAStringconstExp(AStringconstExp node)
    {
        defaultCase(node);
    }

    @Override
    public void caseANullExp(ANullExp node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAObjectReceiver(AObjectReceiver node)
    {
        defaultCase(node);
    }

    @Override
    public void caseASuperReceiver(ASuperReceiver node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTAbstract(TAbstract node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTBoolean(TBoolean node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTBreak(TBreak node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTByte(TByte node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTCase(TCase node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTCatch(TCatch node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTChar(TChar node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTClass(TClass node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTConst(TConst node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTContinue(TContinue node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTDefault(TDefault node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTDo(TDo node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTDouble(TDouble node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTElse(TElse node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTExtends(TExtends node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTExtern(TExtern node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTFinal(TFinal node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTFinally(TFinally node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTFloat(TFloat node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTFor(TFor node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTGoto(TGoto node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTIf(TIf node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTImplements(TImplements node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTImport(TImport node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTIn(TIn node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTInstanceof(TInstanceof node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTInt(TInt node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTInterface(TInterface node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTLong(TLong node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTMain(TMain node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTNative(TNative node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTNew(TNew node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTPackage(TPackage node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTPrivate(TPrivate node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTProtected(TProtected node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTPublic(TPublic node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTReturn(TReturn node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTShort(TShort node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTStatic(TStatic node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTSuper(TSuper node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTSwitch(TSwitch node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTSynchronized(TSynchronized node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTThis(TThis node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTThrow(TThrow node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTThrows(TThrows node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTTransient(TTransient node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTTry(TTry node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTVoid(TVoid node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTVolatile(TVolatile node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTWhile(TWhile node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTAssign(TAssign node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTGt(TGt node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTLt(TLt node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTNot(TNot node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTEq(TEq node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTLeq(TLeq node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTGeq(TGeq node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTNeq(TNeq node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTAnd(TAnd node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTOr(TOr node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTPlus(TPlus node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTMinus(TMinus node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTMult(TMult node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTDiv(TDiv node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTMod(TMod node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTLBrace(TLBrace node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTRBrace(TRBrace node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTSemicolon(TSemicolon node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTLPar(TLPar node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTRPar(TRPar node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTLBracket(TLBracket node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTRBracket(TRBracket node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTComma(TComma node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTDot(TDot node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTInc(TInc node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTNull(TNull node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTTrue(TTrue node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTFalse(TFalse node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTCharconst(TCharconst node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTIntconst(TIntconst node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTStringconst(TStringconst node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTIdentifier(TIdentifier node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTImportpath(TImportpath node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTBlanks(TBlanks node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTEolComment(TEolComment node)
    {
        defaultCase(node);
    }

    @Override
    public void caseEOF(EOF node)
    {
        defaultCase(node);
    }

    @Override
    public void caseInvalidToken(InvalidToken node)
    {
        defaultCase(node);
    }

    public void defaultCase(@SuppressWarnings("unused") Node node)
    {
        // do nothing
    }
}
