/* This file was generated by SableCC (http://www.sablecc.org/). */

package joosc.analysis;

import java.util.*;
import joosc.node.*;

public class DepthFirstAdapter extends AnalysisAdapter
{
    public void inStart(Start node)
    {
        defaultIn(node);
    }

    public void outStart(Start node)
    {
        defaultOut(node);
    }

    public void defaultIn(@SuppressWarnings("unused") Node node)
    {
        // Do nothing
    }

    public void defaultOut(@SuppressWarnings("unused") Node node)
    {
        // Do nothing
    }

    @Override
    public void caseStart(Start node)
    {
        inStart(node);
        node.getPClassfile().apply(this);
        node.getEOF().apply(this);
        outStart(node);
    }

    public void inADefaultClassfile(ADefaultClassfile node)
    {
        defaultIn(node);
    }

    public void outADefaultClassfile(ADefaultClassfile node)
    {
        defaultOut(node);
    }

    @Override
    public void caseADefaultClassfile(ADefaultClassfile node)
    {
        inADefaultClassfile(node);
        if(node.getPClass() != null)
        {
            node.getPClass().apply(this);
        }
        outADefaultClassfile(node);
    }

    public void inAExternClassfile(AExternClassfile node)
    {
        defaultIn(node);
    }

    public void outAExternClassfile(AExternClassfile node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAExternClassfile(AExternClassfile node)
    {
        inAExternClassfile(node);
        {
            List<PExternClass> copy = new ArrayList<PExternClass>(node.getClasses());
            for(PExternClass e : copy)
            {
                e.apply(this);
            }
        }
        outAExternClassfile(node);
    }

    public void inAClass(AClass node)
    {
        defaultIn(node);
    }

    public void outAClass(AClass node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAClass(AClass node)
    {
        inAClass(node);
        if(node.getClassmods() != null)
        {
            node.getClassmods().apply(this);
        }
        if(node.getIdentifier() != null)
        {
            node.getIdentifier().apply(this);
        }
        if(node.getExtension() != null)
        {
            node.getExtension().apply(this);
        }
        {
            List<PField> copy = new ArrayList<PField>(node.getFields());
            for(PField e : copy)
            {
                e.apply(this);
            }
        }
        {
            List<PConstructor> copy = new ArrayList<PConstructor>(node.getConstructors());
            for(PConstructor e : copy)
            {
                e.apply(this);
            }
        }
        {
            List<PMethod> copy = new ArrayList<PMethod>(node.getMethods());
            for(PMethod e : copy)
            {
                e.apply(this);
            }
        }
        outAClass(node);
    }

    public void inAFinalClassmods(AFinalClassmods node)
    {
        defaultIn(node);
    }

    public void outAFinalClassmods(AFinalClassmods node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAFinalClassmods(AFinalClassmods node)
    {
        inAFinalClassmods(node);
        if(node.getFinal() != null)
        {
            node.getFinal().apply(this);
        }
        outAFinalClassmods(node);
    }

    public void inAAbstractClassmods(AAbstractClassmods node)
    {
        defaultIn(node);
    }

    public void outAAbstractClassmods(AAbstractClassmods node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAAbstractClassmods(AAbstractClassmods node)
    {
        inAAbstractClassmods(node);
        if(node.getAbstract() != null)
        {
            node.getAbstract().apply(this);
        }
        outAAbstractClassmods(node);
    }

    public void inAExternClass(AExternClass node)
    {
        defaultIn(node);
    }

    public void outAExternClass(AExternClass node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAExternClass(AExternClass node)
    {
        inAExternClass(node);
        if(node.getClassmods() != null)
        {
            node.getClassmods().apply(this);
        }
        if(node.getIdentifier() != null)
        {
            node.getIdentifier().apply(this);
        }
        if(node.getExtension() != null)
        {
            node.getExtension().apply(this);
        }
        if(node.getStringconst() != null)
        {
            node.getStringconst().apply(this);
        }
        {
            List<PExternConstructor> copy = new ArrayList<PExternConstructor>(node.getConstructors());
            for(PExternConstructor e : copy)
            {
                e.apply(this);
            }
        }
        {
            List<PExternMethod> copy = new ArrayList<PExternMethod>(node.getMethods());
            for(PExternMethod e : copy)
            {
                e.apply(this);
            }
        }
        outAExternClass(node);
    }

    public void inAExtension(AExtension node)
    {
        defaultIn(node);
    }

    public void outAExtension(AExtension node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAExtension(AExtension node)
    {
        inAExtension(node);
        if(node.getIdentifier() != null)
        {
            node.getIdentifier().apply(this);
        }
        outAExtension(node);
    }

    public void inAReferenceType(AReferenceType node)
    {
        defaultIn(node);
    }

    public void outAReferenceType(AReferenceType node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAReferenceType(AReferenceType node)
    {
        inAReferenceType(node);
        if(node.getIdentifier() != null)
        {
            node.getIdentifier().apply(this);
        }
        outAReferenceType(node);
    }

    public void inACharType(ACharType node)
    {
        defaultIn(node);
    }

    public void outACharType(ACharType node)
    {
        defaultOut(node);
    }

    @Override
    public void caseACharType(ACharType node)
    {
        inACharType(node);
        if(node.getChar() != null)
        {
            node.getChar().apply(this);
        }
        outACharType(node);
    }

    public void inABooleanType(ABooleanType node)
    {
        defaultIn(node);
    }

    public void outABooleanType(ABooleanType node)
    {
        defaultOut(node);
    }

    @Override
    public void caseABooleanType(ABooleanType node)
    {
        inABooleanType(node);
        if(node.getBoolean() != null)
        {
            node.getBoolean().apply(this);
        }
        outABooleanType(node);
    }

    public void inAIntType(AIntType node)
    {
        defaultIn(node);
    }

    public void outAIntType(AIntType node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAIntType(AIntType node)
    {
        inAIntType(node);
        if(node.getInt() != null)
        {
            node.getInt().apply(this);
        }
        outAIntType(node);
    }

    public void inAPolynullType(APolynullType node)
    {
        defaultIn(node);
    }

    public void outAPolynullType(APolynullType node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAPolynullType(APolynullType node)
    {
        inAPolynullType(node);
        outAPolynullType(node);
    }

    public void inAVoidType(AVoidType node)
    {
        defaultIn(node);
    }

    public void outAVoidType(AVoidType node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAVoidType(AVoidType node)
    {
        inAVoidType(node);
        outAVoidType(node);
    }

    public void inAFirstField(AFirstField node)
    {
        defaultIn(node);
    }

    public void outAFirstField(AFirstField node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAFirstField(AFirstField node)
    {
        inAFirstField(node);
        if(node.getType() != null)
        {
            node.getType().apply(this);
        }
        {
            List<TIdentifier> copy = new ArrayList<TIdentifier>(node.getIdentifiers());
            for(TIdentifier e : copy)
            {
                e.apply(this);
            }
        }
        outAFirstField(node);
    }

    public void inAField(AField node)
    {
        defaultIn(node);
    }

    public void outAField(AField node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAField(AField node)
    {
        inAField(node);
        {
            List<POnefield> copy = new ArrayList<POnefield>(node.getFields());
            for(POnefield e : copy)
            {
                e.apply(this);
            }
        }
        outAField(node);
    }

    public void inAOnefield(AOnefield node)
    {
        defaultIn(node);
    }

    public void outAOnefield(AOnefield node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAOnefield(AOnefield node)
    {
        inAOnefield(node);
        if(node.getType() != null)
        {
            node.getType().apply(this);
        }
        if(node.getIdentifier() != null)
        {
            node.getIdentifier().apply(this);
        }
        outAOnefield(node);
    }

    public void inAConstructor(AConstructor node)
    {
        defaultIn(node);
    }

    public void outAConstructor(AConstructor node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAConstructor(AConstructor node)
    {
        inAConstructor(node);
        if(node.getIdentifier() != null)
        {
            node.getIdentifier().apply(this);
        }
        {
            List<PFormal> copy = new ArrayList<PFormal>(node.getFormals());
            for(PFormal e : copy)
            {
                e.apply(this);
            }
        }
        {
            List<PStm> copy = new ArrayList<PStm>(node.getStmts());
            for(PStm e : copy)
            {
                e.apply(this);
            }
        }
        outAConstructor(node);
    }

    public void inAExternConstructor(AExternConstructor node)
    {
        defaultIn(node);
    }

    public void outAExternConstructor(AExternConstructor node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAExternConstructor(AExternConstructor node)
    {
        inAExternConstructor(node);
        if(node.getIdentifier() != null)
        {
            node.getIdentifier().apply(this);
        }
        {
            List<PFormal> copy = new ArrayList<PFormal>(node.getFormals());
            for(PFormal e : copy)
            {
                e.apply(this);
            }
        }
        outAExternConstructor(node);
    }

    public void inAFormal(AFormal node)
    {
        defaultIn(node);
    }

    public void outAFormal(AFormal node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAFormal(AFormal node)
    {
        inAFormal(node);
        if(node.getType() != null)
        {
            node.getType().apply(this);
        }
        if(node.getIdentifier() != null)
        {
            node.getIdentifier().apply(this);
        }
        outAFormal(node);
    }

    public void inAModMethod(AModMethod node)
    {
        defaultIn(node);
    }

    public void outAModMethod(AModMethod node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAModMethod(AModMethod node)
    {
        inAModMethod(node);
        if(node.getMethodmods() != null)
        {
            node.getMethodmods().apply(this);
        }
        if(node.getReturntype() != null)
        {
            node.getReturntype().apply(this);
        }
        if(node.getIdentifier() != null)
        {
            node.getIdentifier().apply(this);
        }
        {
            List<PFormal> copy = new ArrayList<PFormal>(node.getFormals());
            for(PFormal e : copy)
            {
                e.apply(this);
            }
        }
        {
            List<PStm> copy = new ArrayList<PStm>(node.getStmts());
            for(PStm e : copy)
            {
                e.apply(this);
            }
        }
        outAModMethod(node);
    }

    public void inANonmodMethod(ANonmodMethod node)
    {
        defaultIn(node);
    }

    public void outANonmodMethod(ANonmodMethod node)
    {
        defaultOut(node);
    }

    @Override
    public void caseANonmodMethod(ANonmodMethod node)
    {
        inANonmodMethod(node);
        if(node.getReturntype() != null)
        {
            node.getReturntype().apply(this);
        }
        if(node.getIdentifier() != null)
        {
            node.getIdentifier().apply(this);
        }
        {
            List<PFormal> copy = new ArrayList<PFormal>(node.getFormals());
            for(PFormal e : copy)
            {
                e.apply(this);
            }
        }
        {
            List<PStm> copy = new ArrayList<PStm>(node.getStmts());
            for(PStm e : copy)
            {
                e.apply(this);
            }
        }
        outANonmodMethod(node);
    }

    public void inAAbstractMethod(AAbstractMethod node)
    {
        defaultIn(node);
    }

    public void outAAbstractMethod(AAbstractMethod node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAAbstractMethod(AAbstractMethod node)
    {
        inAAbstractMethod(node);
        if(node.getReturntype() != null)
        {
            node.getReturntype().apply(this);
        }
        if(node.getIdentifier() != null)
        {
            node.getIdentifier().apply(this);
        }
        {
            List<PFormal> copy = new ArrayList<PFormal>(node.getFormals());
            for(PFormal e : copy)
            {
                e.apply(this);
            }
        }
        outAAbstractMethod(node);
    }

    public void inAMainMethod(AMainMethod node)
    {
        defaultIn(node);
    }

    public void outAMainMethod(AMainMethod node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAMainMethod(AMainMethod node)
    {
        inAMainMethod(node);
        if(node.getMainargv() != null)
        {
            node.getMainargv().apply(this);
        }
        {
            List<PStm> copy = new ArrayList<PStm>(node.getStmts());
            for(PStm e : copy)
            {
                e.apply(this);
            }
        }
        outAMainMethod(node);
    }

    public void inAFinalMethodmods(AFinalMethodmods node)
    {
        defaultIn(node);
    }

    public void outAFinalMethodmods(AFinalMethodmods node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAFinalMethodmods(AFinalMethodmods node)
    {
        inAFinalMethodmods(node);
        if(node.getFinal() != null)
        {
            node.getFinal().apply(this);
        }
        outAFinalMethodmods(node);
    }

    public void inASynchronizedMethodmods(ASynchronizedMethodmods node)
    {
        defaultIn(node);
    }

    public void outASynchronizedMethodmods(ASynchronizedMethodmods node)
    {
        defaultOut(node);
    }

    @Override
    public void caseASynchronizedMethodmods(ASynchronizedMethodmods node)
    {
        inASynchronizedMethodmods(node);
        if(node.getSynchronized() != null)
        {
            node.getSynchronized().apply(this);
        }
        outASynchronizedMethodmods(node);
    }

    public void inAMainargv(AMainargv node)
    {
        defaultIn(node);
    }

    public void outAMainargv(AMainargv node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAMainargv(AMainargv node)
    {
        inAMainargv(node);
        if(node.getType() != null)
        {
            node.getType().apply(this);
        }
        if(node.getName() != null)
        {
            node.getName().apply(this);
        }
        outAMainargv(node);
    }

    public void inAModExternMethod(AModExternMethod node)
    {
        defaultIn(node);
    }

    public void outAModExternMethod(AModExternMethod node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAModExternMethod(AModExternMethod node)
    {
        inAModExternMethod(node);
        if(node.getExternMethodmods() != null)
        {
            node.getExternMethodmods().apply(this);
        }
        if(node.getReturntype() != null)
        {
            node.getReturntype().apply(this);
        }
        if(node.getIdentifier() != null)
        {
            node.getIdentifier().apply(this);
        }
        {
            List<PFormal> copy = new ArrayList<PFormal>(node.getFormals());
            for(PFormal e : copy)
            {
                e.apply(this);
            }
        }
        outAModExternMethod(node);
    }

    public void inANonmodExternMethod(ANonmodExternMethod node)
    {
        defaultIn(node);
    }

    public void outANonmodExternMethod(ANonmodExternMethod node)
    {
        defaultOut(node);
    }

    @Override
    public void caseANonmodExternMethod(ANonmodExternMethod node)
    {
        inANonmodExternMethod(node);
        if(node.getReturntype() != null)
        {
            node.getReturntype().apply(this);
        }
        if(node.getIdentifier() != null)
        {
            node.getIdentifier().apply(this);
        }
        {
            List<PFormal> copy = new ArrayList<PFormal>(node.getFormals());
            for(PFormal e : copy)
            {
                e.apply(this);
            }
        }
        outANonmodExternMethod(node);
    }

    public void inAFinalExternMethodmods(AFinalExternMethodmods node)
    {
        defaultIn(node);
    }

    public void outAFinalExternMethodmods(AFinalExternMethodmods node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAFinalExternMethodmods(AFinalExternMethodmods node)
    {
        inAFinalExternMethodmods(node);
        if(node.getFinal() != null)
        {
            node.getFinal().apply(this);
        }
        outAFinalExternMethodmods(node);
    }

    public void inAAbstractExternMethodmods(AAbstractExternMethodmods node)
    {
        defaultIn(node);
    }

    public void outAAbstractExternMethodmods(AAbstractExternMethodmods node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAAbstractExternMethodmods(AAbstractExternMethodmods node)
    {
        inAAbstractExternMethodmods(node);
        if(node.getAbstract() != null)
        {
            node.getAbstract().apply(this);
        }
        outAAbstractExternMethodmods(node);
    }

    public void inASynchronizedExternMethodmods(ASynchronizedExternMethodmods node)
    {
        defaultIn(node);
    }

    public void outASynchronizedExternMethodmods(ASynchronizedExternMethodmods node)
    {
        defaultOut(node);
    }

    @Override
    public void caseASynchronizedExternMethodmods(ASynchronizedExternMethodmods node)
    {
        inASynchronizedExternMethodmods(node);
        if(node.getSynchronized() != null)
        {
            node.getSynchronized().apply(this);
        }
        outASynchronizedExternMethodmods(node);
    }

    public void inAVoidReturntype(AVoidReturntype node)
    {
        defaultIn(node);
    }

    public void outAVoidReturntype(AVoidReturntype node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAVoidReturntype(AVoidReturntype node)
    {
        inAVoidReturntype(node);
        outAVoidReturntype(node);
    }

    public void inANonvoidReturntype(ANonvoidReturntype node)
    {
        defaultIn(node);
    }

    public void outANonvoidReturntype(ANonvoidReturntype node)
    {
        defaultOut(node);
    }

    @Override
    public void caseANonvoidReturntype(ANonvoidReturntype node)
    {
        inANonvoidReturntype(node);
        if(node.getType() != null)
        {
            node.getType().apply(this);
        }
        outANonvoidReturntype(node);
    }

    public void inASkipStm(ASkipStm node)
    {
        defaultIn(node);
    }

    public void outASkipStm(ASkipStm node)
    {
        defaultOut(node);
    }

    @Override
    public void caseASkipStm(ASkipStm node)
    {
        inASkipStm(node);
        outASkipStm(node);
    }

    public void inABlockStm(ABlockStm node)
    {
        defaultIn(node);
    }

    public void outABlockStm(ABlockStm node)
    {
        defaultOut(node);
    }

    @Override
    public void caseABlockStm(ABlockStm node)
    {
        inABlockStm(node);
        {
            List<PStm> copy = new ArrayList<PStm>(node.getStmts());
            for(PStm e : copy)
            {
                e.apply(this);
            }
        }
        outABlockStm(node);
    }

    public void inAExpStm(AExpStm node)
    {
        defaultIn(node);
    }

    public void outAExpStm(AExpStm node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAExpStm(AExpStm node)
    {
        inAExpStm(node);
        if(node.getExp() != null)
        {
            node.getExp().apply(this);
        }
        outAExpStm(node);
    }

    public void inAReturnStm(AReturnStm node)
    {
        defaultIn(node);
    }

    public void outAReturnStm(AReturnStm node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAReturnStm(AReturnStm node)
    {
        inAReturnStm(node);
        if(node.getExp() != null)
        {
            node.getExp().apply(this);
        }
        outAReturnStm(node);
    }

    public void inADeclFirstStm(ADeclFirstStm node)
    {
        defaultIn(node);
    }

    public void outADeclFirstStm(ADeclFirstStm node)
    {
        defaultOut(node);
    }

    @Override
    public void caseADeclFirstStm(ADeclFirstStm node)
    {
        inADeclFirstStm(node);
        if(node.getType() != null)
        {
            node.getType().apply(this);
        }
        {
            List<TIdentifier> copy = new ArrayList<TIdentifier>(node.getIdentifiers());
            for(TIdentifier e : copy)
            {
                e.apply(this);
            }
        }
        outADeclFirstStm(node);
    }

    public void inADeclStm(ADeclStm node)
    {
        defaultIn(node);
    }

    public void outADeclStm(ADeclStm node)
    {
        defaultOut(node);
    }

    @Override
    public void caseADeclStm(ADeclStm node)
    {
        inADeclStm(node);
        {
            List<POnelocal> copy = new ArrayList<POnelocal>(node.getLocals());
            for(POnelocal e : copy)
            {
                e.apply(this);
            }
        }
        outADeclStm(node);
    }

    public void inASuperconsStm(ASuperconsStm node)
    {
        defaultIn(node);
    }

    public void outASuperconsStm(ASuperconsStm node)
    {
        defaultOut(node);
    }

    @Override
    public void caseASuperconsStm(ASuperconsStm node)
    {
        inASuperconsStm(node);
        {
            List<PExp> copy = new ArrayList<PExp>(node.getArgs());
            for(PExp e : copy)
            {
                e.apply(this);
            }
        }
        outASuperconsStm(node);
    }

    public void inAIfStm(AIfStm node)
    {
        defaultIn(node);
    }

    public void outAIfStm(AIfStm node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAIfStm(AIfStm node)
    {
        inAIfStm(node);
        if(node.getExp() != null)
        {
            node.getExp().apply(this);
        }
        if(node.getStm() != null)
        {
            node.getStm().apply(this);
        }
        outAIfStm(node);
    }

    public void inAIfelseStm(AIfelseStm node)
    {
        defaultIn(node);
    }

    public void outAIfelseStm(AIfelseStm node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAIfelseStm(AIfelseStm node)
    {
        inAIfelseStm(node);
        if(node.getExp() != null)
        {
            node.getExp().apply(this);
        }
        if(node.getThenStm() != null)
        {
            node.getThenStm().apply(this);
        }
        if(node.getElseStm() != null)
        {
            node.getElseStm().apply(this);
        }
        outAIfelseStm(node);
    }

    public void inAWhileStm(AWhileStm node)
    {
        defaultIn(node);
    }

    public void outAWhileStm(AWhileStm node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAWhileStm(AWhileStm node)
    {
        inAWhileStm(node);
        if(node.getExp() != null)
        {
            node.getExp().apply(this);
        }
        if(node.getStm() != null)
        {
            node.getStm().apply(this);
        }
        outAWhileStm(node);
    }

    public void inAOnelocal(AOnelocal node)
    {
        defaultIn(node);
    }

    public void outAOnelocal(AOnelocal node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAOnelocal(AOnelocal node)
    {
        inAOnelocal(node);
        if(node.getType() != null)
        {
            node.getType().apply(this);
        }
        if(node.getIdentifier() != null)
        {
            node.getIdentifier().apply(this);
        }
        outAOnelocal(node);
    }

    public void inAAssignExp(AAssignExp node)
    {
        defaultIn(node);
    }

    public void outAAssignExp(AAssignExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAAssignExp(AAssignExp node)
    {
        inAAssignExp(node);
        if(node.getIdentifier() != null)
        {
            node.getIdentifier().apply(this);
        }
        if(node.getExp() != null)
        {
            node.getExp().apply(this);
        }
        outAAssignExp(node);
    }

    public void inAOrExp(AOrExp node)
    {
        defaultIn(node);
    }

    public void outAOrExp(AOrExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAOrExp(AOrExp node)
    {
        inAOrExp(node);
        if(node.getLeft() != null)
        {
            node.getLeft().apply(this);
        }
        if(node.getRight() != null)
        {
            node.getRight().apply(this);
        }
        outAOrExp(node);
    }

    public void inAAndExp(AAndExp node)
    {
        defaultIn(node);
    }

    public void outAAndExp(AAndExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAAndExp(AAndExp node)
    {
        inAAndExp(node);
        if(node.getLeft() != null)
        {
            node.getLeft().apply(this);
        }
        if(node.getRight() != null)
        {
            node.getRight().apply(this);
        }
        outAAndExp(node);
    }

    public void inAEqExp(AEqExp node)
    {
        defaultIn(node);
    }

    public void outAEqExp(AEqExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAEqExp(AEqExp node)
    {
        inAEqExp(node);
        if(node.getLeft() != null)
        {
            node.getLeft().apply(this);
        }
        if(node.getRight() != null)
        {
            node.getRight().apply(this);
        }
        outAEqExp(node);
    }

    public void inANeqExp(ANeqExp node)
    {
        defaultIn(node);
    }

    public void outANeqExp(ANeqExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseANeqExp(ANeqExp node)
    {
        inANeqExp(node);
        if(node.getLeft() != null)
        {
            node.getLeft().apply(this);
        }
        if(node.getRight() != null)
        {
            node.getRight().apply(this);
        }
        outANeqExp(node);
    }

    public void inALtExp(ALtExp node)
    {
        defaultIn(node);
    }

    public void outALtExp(ALtExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseALtExp(ALtExp node)
    {
        inALtExp(node);
        if(node.getLeft() != null)
        {
            node.getLeft().apply(this);
        }
        if(node.getRight() != null)
        {
            node.getRight().apply(this);
        }
        outALtExp(node);
    }

    public void inAGtExp(AGtExp node)
    {
        defaultIn(node);
    }

    public void outAGtExp(AGtExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAGtExp(AGtExp node)
    {
        inAGtExp(node);
        if(node.getLeft() != null)
        {
            node.getLeft().apply(this);
        }
        if(node.getRight() != null)
        {
            node.getRight().apply(this);
        }
        outAGtExp(node);
    }

    public void inALeqExp(ALeqExp node)
    {
        defaultIn(node);
    }

    public void outALeqExp(ALeqExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseALeqExp(ALeqExp node)
    {
        inALeqExp(node);
        if(node.getLeft() != null)
        {
            node.getLeft().apply(this);
        }
        if(node.getRight() != null)
        {
            node.getRight().apply(this);
        }
        outALeqExp(node);
    }

    public void inAGeqExp(AGeqExp node)
    {
        defaultIn(node);
    }

    public void outAGeqExp(AGeqExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAGeqExp(AGeqExp node)
    {
        inAGeqExp(node);
        if(node.getLeft() != null)
        {
            node.getLeft().apply(this);
        }
        if(node.getRight() != null)
        {
            node.getRight().apply(this);
        }
        outAGeqExp(node);
    }

    public void inAInstanceofExp(AInstanceofExp node)
    {
        defaultIn(node);
    }

    public void outAInstanceofExp(AInstanceofExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAInstanceofExp(AInstanceofExp node)
    {
        inAInstanceofExp(node);
        if(node.getExp() != null)
        {
            node.getExp().apply(this);
        }
        if(node.getIdentifier() != null)
        {
            node.getIdentifier().apply(this);
        }
        outAInstanceofExp(node);
    }

    public void inAPlusExp(APlusExp node)
    {
        defaultIn(node);
    }

    public void outAPlusExp(APlusExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAPlusExp(APlusExp node)
    {
        inAPlusExp(node);
        if(node.getLeft() != null)
        {
            node.getLeft().apply(this);
        }
        if(node.getRight() != null)
        {
            node.getRight().apply(this);
        }
        outAPlusExp(node);
    }

    public void inAMinusExp(AMinusExp node)
    {
        defaultIn(node);
    }

    public void outAMinusExp(AMinusExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAMinusExp(AMinusExp node)
    {
        inAMinusExp(node);
        if(node.getLeft() != null)
        {
            node.getLeft().apply(this);
        }
        if(node.getRight() != null)
        {
            node.getRight().apply(this);
        }
        outAMinusExp(node);
    }

    public void inAMultExp(AMultExp node)
    {
        defaultIn(node);
    }

    public void outAMultExp(AMultExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAMultExp(AMultExp node)
    {
        inAMultExp(node);
        if(node.getLeft() != null)
        {
            node.getLeft().apply(this);
        }
        if(node.getRight() != null)
        {
            node.getRight().apply(this);
        }
        outAMultExp(node);
    }

    public void inADivExp(ADivExp node)
    {
        defaultIn(node);
    }

    public void outADivExp(ADivExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseADivExp(ADivExp node)
    {
        inADivExp(node);
        if(node.getLeft() != null)
        {
            node.getLeft().apply(this);
        }
        if(node.getRight() != null)
        {
            node.getRight().apply(this);
        }
        outADivExp(node);
    }

    public void inAModExp(AModExp node)
    {
        defaultIn(node);
    }

    public void outAModExp(AModExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAModExp(AModExp node)
    {
        inAModExp(node);
        if(node.getLeft() != null)
        {
            node.getLeft().apply(this);
        }
        if(node.getRight() != null)
        {
            node.getRight().apply(this);
        }
        outAModExp(node);
    }

    public void inAUminusExp(AUminusExp node)
    {
        defaultIn(node);
    }

    public void outAUminusExp(AUminusExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAUminusExp(AUminusExp node)
    {
        inAUminusExp(node);
        if(node.getExp() != null)
        {
            node.getExp().apply(this);
        }
        outAUminusExp(node);
    }

    public void inANotExp(ANotExp node)
    {
        defaultIn(node);
    }

    public void outANotExp(ANotExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseANotExp(ANotExp node)
    {
        inANotExp(node);
        if(node.getExp() != null)
        {
            node.getExp().apply(this);
        }
        outANotExp(node);
    }

    public void inATmpcastExp(ATmpcastExp node)
    {
        defaultIn(node);
    }

    public void outATmpcastExp(ATmpcastExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseATmpcastExp(ATmpcastExp node)
    {
        inATmpcastExp(node);
        if(node.getCaster() != null)
        {
            node.getCaster().apply(this);
        }
        if(node.getCastee() != null)
        {
            node.getCastee().apply(this);
        }
        outATmpcastExp(node);
    }

    public void inACastExp(ACastExp node)
    {
        defaultIn(node);
    }

    public void outACastExp(ACastExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseACastExp(ACastExp node)
    {
        inACastExp(node);
        if(node.getIdentifier() != null)
        {
            node.getIdentifier().apply(this);
        }
        if(node.getExp() != null)
        {
            node.getExp().apply(this);
        }
        outACastExp(node);
    }

    public void inACasttocharExp(ACasttocharExp node)
    {
        defaultIn(node);
    }

    public void outACasttocharExp(ACasttocharExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseACasttocharExp(ACasttocharExp node)
    {
        inACasttocharExp(node);
        if(node.getExp() != null)
        {
            node.getExp().apply(this);
        }
        outACasttocharExp(node);
    }

    public void inAIdExp(AIdExp node)
    {
        defaultIn(node);
    }

    public void outAIdExp(AIdExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAIdExp(AIdExp node)
    {
        inAIdExp(node);
        if(node.getIdentifier() != null)
        {
            node.getIdentifier().apply(this);
        }
        outAIdExp(node);
    }

    public void inAThisExp(AThisExp node)
    {
        defaultIn(node);
    }

    public void outAThisExp(AThisExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAThisExp(AThisExp node)
    {
        inAThisExp(node);
        outAThisExp(node);
    }

    public void inANewExp(ANewExp node)
    {
        defaultIn(node);
    }

    public void outANewExp(ANewExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseANewExp(ANewExp node)
    {
        inANewExp(node);
        if(node.getIdentifier() != null)
        {
            node.getIdentifier().apply(this);
        }
        {
            List<PExp> copy = new ArrayList<PExp>(node.getArgs());
            for(PExp e : copy)
            {
                e.apply(this);
            }
        }
        outANewExp(node);
    }

    public void inACallExp(ACallExp node)
    {
        defaultIn(node);
    }

    public void outACallExp(ACallExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseACallExp(ACallExp node)
    {
        inACallExp(node);
        if(node.getReceiver() != null)
        {
            node.getReceiver().apply(this);
        }
        if(node.getIdentifier() != null)
        {
            node.getIdentifier().apply(this);
        }
        {
            List<PExp> copy = new ArrayList<PExp>(node.getArgs());
            for(PExp e : copy)
            {
                e.apply(this);
            }
        }
        outACallExp(node);
    }

    public void inAIntconstExp(AIntconstExp node)
    {
        defaultIn(node);
    }

    public void outAIntconstExp(AIntconstExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAIntconstExp(AIntconstExp node)
    {
        inAIntconstExp(node);
        if(node.getIntconst() != null)
        {
            node.getIntconst().apply(this);
        }
        outAIntconstExp(node);
    }

    public void inATrueExp(ATrueExp node)
    {
        defaultIn(node);
    }

    public void outATrueExp(ATrueExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseATrueExp(ATrueExp node)
    {
        inATrueExp(node);
        outATrueExp(node);
    }

    public void inAFalseExp(AFalseExp node)
    {
        defaultIn(node);
    }

    public void outAFalseExp(AFalseExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAFalseExp(AFalseExp node)
    {
        inAFalseExp(node);
        outAFalseExp(node);
    }

    public void inACharconstExp(ACharconstExp node)
    {
        defaultIn(node);
    }

    public void outACharconstExp(ACharconstExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseACharconstExp(ACharconstExp node)
    {
        inACharconstExp(node);
        if(node.getCharconst() != null)
        {
            node.getCharconst().apply(this);
        }
        outACharconstExp(node);
    }

    public void inAStringconstExp(AStringconstExp node)
    {
        defaultIn(node);
    }

    public void outAStringconstExp(AStringconstExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAStringconstExp(AStringconstExp node)
    {
        inAStringconstExp(node);
        if(node.getStringconst() != null)
        {
            node.getStringconst().apply(this);
        }
        outAStringconstExp(node);
    }

    public void inANullExp(ANullExp node)
    {
        defaultIn(node);
    }

    public void outANullExp(ANullExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseANullExp(ANullExp node)
    {
        inANullExp(node);
        outANullExp(node);
    }

    public void inAObjectReceiver(AObjectReceiver node)
    {
        defaultIn(node);
    }

    public void outAObjectReceiver(AObjectReceiver node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAObjectReceiver(AObjectReceiver node)
    {
        inAObjectReceiver(node);
        if(node.getExp() != null)
        {
            node.getExp().apply(this);
        }
        outAObjectReceiver(node);
    }

    public void inASuperReceiver(ASuperReceiver node)
    {
        defaultIn(node);
    }

    public void outASuperReceiver(ASuperReceiver node)
    {
        defaultOut(node);
    }

    @Override
    public void caseASuperReceiver(ASuperReceiver node)
    {
        inASuperReceiver(node);
        outASuperReceiver(node);
    }
}
